### PR TITLE
Example refactor /code sharing of temperature

### PR DESCRIPTION
**Pull request by khcnz**
Hey Scotty, if you are making this level of changes in a new repo I'd suggest a couple of further changes (which I'm happy to help with if you agree).

1) Standard get methods (such as get temperature) shouldn't return json but should just return the data requested directly - thats how the old library worked at an interface level right?
2) A bunch of code sharing can be used in some places to greatly reduce template code

Let me know your thoughts, happy to help out with more.

### CODE REVIEW

**Comment by khcnz** [comment]
I think these changes would break how update() currently works, but that would be an easy fix.

**Comment by scottyphillips** [comment]
I’ll have a think about it and let you know

**Comment by scottyphillips** [comment]
Ive almost made all these changes but ill include the single message response function tomorrow.

**Comment by scottyphillips** [comment]
Closing this now as intent has been realised

**Pull request closed without merging**
